const actionTypes = {
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  SOCIAL_LOGIN: "SOCIAL_LOGIN",
  SOCIAL_LOGIN_CALLBACK: "SOCIAL_LOGIN_CALLBACK",
  GET_USER_ACCOUNT_TYPE: "GET_USER_ACCOUNT_TYPE",
  LOGOUT: "LOGOUT",

  // Posts
  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_NEW_POSTS: "GET_NEW_POSTS",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  CREATE_POST: "CREATE_POST",
  GET_POSTS_OF_USER: "GET_POSTS_OF_USER",

  // Categories
  GET_CATEGORY: "GET_CATEGORY",

  // Prices
  GET_PRICES: "GET_PRICES",

  // Areas
  GET_AREAS: "GET_AREAS",

  // Provinces
  GET_PROVINCES: "GET_PROVINCES",

  // Users
  GET_USER_DETAIL: "GET_USER_DETAIL",
};

export default actionTypes;
