name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Generate timestamp-based tag (yyyyMMddHHmm)
    - name: Generate timestamp-based tag
      id: timestamp
      run: echo "TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    # Step 3: Downcase
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    # Step 4: Build and tag the Docker image
    - name: Build Docker image
      run: |
        docker build --build-arg REACT_APP_SERVER_URL=https://4g.std.io.vn/backend -t ghcr.io/${{ env.REPO }}/rental-client:${{ env.TAG }} -t ghcr.io/${{ env.REPO }}/rental-client:latest .

    # Step 5: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Push Docker Image to GitHub Container Registry
    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ env.REPO }}/rental-client:${{ env.TAG }}
        docker push ghcr.io/${{ env.REPO }}/rental-client:latest